In [114]:
import pandas as pd
data = pd.read_csv('new_data_Rl.csv')
data

Self velocity(m/s)  Object velocity         Range     Tolerance  \
0              2.695980        14.831661  8.924739e-01  2.677422e-01   
1              0.424813        27.626374  2.215940e-02  6.647820e-03   
2              1.698926        25.085117  3.544143e-01  1.063243e-01   
3              1.656997        31.651436  3.371362e-01  1.011409e-01   
4              0.000955        14.149802  1.119369e-07  3.358108e-08   
..                  ...              ...           ...           ...   
175           40.618150        31.982310  2.025828e+02  6.077483e+01   
176           41.224242         1.912417  2.086736e+02  6.260209e+01   
177           40.786915         6.182747  2.042697e+02  6.128091e+01   
178           39.910413        31.372349  1.955846e+02  5.867538e+01   
179           40.711693        27.118171  2.035169e+02  6.105508e+01   

     Range + Tolerance      Distance     Collision  
0         1.160216e+00  1.784948e-01 -9.817213e-01  
1         2.880722e-02  4.431880e-03 -2.437534e-02  
2         4.607386e-01  7.088286e-02 -3.898557e-01  
3         4.382771e-01  6.742725e-02 -3.708498e-01  
4         1.455180e-07  2.238739e-08 -1.231306e-07  
..                 ...           ...           ...  
175       2.633576e+02  1.620662e+02 -1.012914e+02  
176       2.712757e+02  1.669389e+02 -1.043368e+02  
177       2.655506e+02  1.634158e+02 -1.021348e+02  
178       2.542600e+02  1.564677e+02 -9.779231e+01  
179       2.645720e+02  1.628135e+02 -1.017585e+02  

[180 rows x 7 columns]

In [115]:
df = pd.DataFrame(data, columns= ['Self velocity(m/s)','Object velocity','Range','Tolerance','range+tolerance','Distance'])
df

Self velocity(m/s)  Object velocity         Range     Tolerance  \
0              2.695980        14.831661  8.924739e-01  2.677422e-01   
1              0.424813        27.626374  2.215940e-02  6.647820e-03   
2              1.698926        25.085117  3.544143e-01  1.063243e-01   
3              1.656997        31.651436  3.371362e-01  1.011409e-01   
4              0.000955        14.149802  1.119369e-07  3.358108e-08   
..                  ...              ...           ...           ...   
175           40.618150        31.982310  2.025828e+02  6.077483e+01   
176           41.224242         1.912417  2.086736e+02  6.260209e+01   
177           40.786915         6.182747  2.042697e+02  6.128091e+01   
178           39.910413        31.372349  1.955846e+02  5.867538e+01   
179           40.711693        27.118171  2.035169e+02  6.105508e+01   

     range+tolerance      Distance  
0                NaN  1.784948e-01  
1                NaN  4.431880e-03  
2                NaN  7.088286e-02  
3                NaN  6.742725e-02  
4                NaN  2.238739e-08  
..               ...           ...  
175              NaN  1.620662e+02  
176              NaN  1.669389e+02  
177              NaN  1.634158e+02  
178              NaN  1.564677e+02  
179              NaN  1.628135e+02  

[180 rows x 6 columns]

In [132]:
df.describe()

Self velocity(m/s)  Object velocity         Range     Tolerance  \
count          180.000000       180.000000  1.800000e+02  1.800000e+02   
mean            21.252501        22.259358  7.334669e+01  2.200401e+01   
std             12.102910        11.942684  6.490067e+01  1.947020e+01   
min              0.000955         1.064866  1.119369e-07  3.358108e-08   
25%             11.033206        13.886978  1.494834e+01  4.484502e+00   
50%             21.177819        24.000000  5.507345e+01  1.652203e+01   
75%             32.056722        31.466073  1.261832e+02  3.785497e+01   
max             41.298987        41.999520  2.094310e+02  6.282931e+01   

       range+tolerance      Distance  
count              0.0  1.800000e+02  
mean               NaN  6.601779e+01  
std                NaN  6.222011e+01  
min                NaN  2.238739e-08  
25%                NaN  2.989668e+00  
50%                NaN  3.304407e+01  
75%                NaN  1.257675e+02  
max                NaN  1.675448e+02

In [116]:
nadf = df.to_numpy()

In [117]:
nadf[0,0]

2.695979942

In [118]:
len(nadf)

180

In [119]:
df.iloc[i,2]

1.119369347e-07

In [120]:
df.loc[:,['Self velocity(m/s)']]

Self velocity(m/s)
0              2.695980
1              0.424813
2              1.698926
3              1.656997
4              0.000955
..                  ...
175           40.618150
176           41.224242
177           40.786915
178           39.910413
179           40.711693

[180 rows x 1 columns]

In [121]:

SV = list(df['Self velocity(m/s)'])
OV = list(df['Object velocity'])
DO = list(df['Distance'])
RG = list(df['range+tolerance'])




In [122]:
actions_space = ['Break','Agg.break','Acc','DeAcc','No Actions']
state_space = [2.77,5.55,8.33,11.11,13.38,16.11,19.44,22.22,25,27.77,30.55,33.33,36.11,38.88,41.66]
print(actions_space)
print(state_space)
print(len(state_space))

['Break', 'Agg.break', 'Acc', 'DeAcc', 'No Actions']
[2.77, 5.55, 8.33, 11.11, 13.38, 16.11, 19.44, 22.22, 25, 27.77, 30.55, 33.33, 36.11, 38.88, 41.66]
15


In [123]:
import numpy as np  
q_table = np.zeros((15,5))
q_table


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# **Make State**

In [124]:
def make_state(SV):
    if(SV <=2.77):
        return  0
    elif(SV > 2.77 and SV <= 5.77):
         return 1
    elif(SV > 5.55 and SV <=8.33):
        return 2
    elif(SV > 8.33 and SV <=11.11):
        return 3      
    elif(SV > 11.11 and SV <=13.38):
        return 4
    elif(SV>13.38 and SV<=16.66):
        return 5
    elif(SV > 16.66 and SV <=19.44):
        return 6
    elif(SV > 19.44 and SV <=22.22):
        return 7
    elif(SV > 22.22 and SV<=25):
        return 8
    elif (SV > 25 and SV<=27.77):
        return 9
    elif (SV > 27.77 and SV<=30.55):
        return 10
    elif (SV > 30.55 and SV<=33.33):
        return 11
    elif (SV > 33.33 and SV<=36.11):
        return 12
    elif (SV > 36.11 and SV<=38.88):
        return 13
    else :
        return 14


# REWARD FUNCTION

# **Actions**

In [125]:
def get_next_action(current_row_index, current_column_index, epsilon):
  #if a randomly chosen value between 0 and 1 is less than epsilon, 
  #then choose the most promising value from the Q-table for this state.  
  if np.random.random() < epsilon:
    return np.argmax(q_values[current_row_index, current_column_index])
  else: #choose a random action
    return np.random.randint(4)


# **Next State Function**

In [141]:

def next_state(state,action,SV,OV,ds,reward):
    
    if(action==0):
        SV = SV - 2.77
    elif(action==1):
        SV = SV-5
    elif(action==2):
        SV = SV+5
    elif(action==3):
        SV = SV+4
    elif(action==4):
        SV = SV-0.1
        
    a = 2.77
    x = (OV+SV)/2.5
    d=(pow(OV,2)/(2*a))
    rg = float(x+d)
    if(rg>ds):
        reward = 1
    else:
        reward = -1
    
    state = make_state(SV)
    
    return(int(state),reward)

# **Reward Table**

In [142]:
import random
    
epsilon = 0.1 #the percentage of time when we should take the best action (instead of a random action)
gamma = 0.4#discount factor for future rewards
alpha = 0.1 #the rate at which the AI agent should learn

all_epochs = []
all_penalties = []


#for i in range(1, 5):

for j in range(len(nadf)):    
    #print(index, " ",row['Object Velocity'])
    
    state = make_state(nadf[j,0])
    epochs, penalties, reward, = 0, 0, 0
        #done = False
        #while not done:
        
    if random.uniform(0, 1) > epsilon:
         action = random.randint(0,4) # Explore action space
    else:
         action = np.argmax(q_table[state]) # Exploit learned values

        
    old_value = q_table[state, action]
    next_s,reward = next_state(state,action,nadf[j,0],nadf[j,1],nadf[j,5],reward)
    next_max = np.max(q_table[next_s])

    new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
    q_table[state, action] = new_value
        
        #if reward == 100:
        #done = True
            
    if reward==-1:
        penalties+=1
                
                
        epochs += 1
        
    '''if i % 100 == 0:
        clear_output(wait=True)
        print(f"Episode: {i}")'''

print("Training finished.\n")
print("Penalties :- ",penalties)
print("Reward:-",reward)
print(q_table)

        

        



            
        
        
        
        

Training finished.

Penalties :-  1
Reward:- -1
[[ 2.45357133  2.34047687  2.52595174  1.80136045  2.41667948]
 [ 2.18782357  2.19444564  2.53215116  1.95016872  2.38232485]
 [ 2.52666476  2.53732395  2.50113294  2.56634442  2.09157218]
 [ 2.58182458  2.6264077   2.45266611  2.5188928   1.99902118]
 [ 2.14723348  2.57483836  2.19550815  2.12581345  1.88989871]
 [ 2.35991122  2.49574253  1.85424135  2.48965048  2.35968439]
 [ 2.05383228  2.06463356  2.1575968   1.70289898  1.36516638]
 [ 1.63660164  1.41437801  1.81723143  1.63662786  1.27946773]
 [ 1.19249924  1.20764602  0.58657726  0.87102361  1.2280237 ]
 [ 1.42898691  1.34912116  0.7678962   1.11220553  0.52174441]
 [ 0.57232049  0.88150792  0.65733642  1.00391566  0.26701938]
 [ 1.76740253  2.06068708  1.550578    2.04554974  1.99168306]
 [ 1.19335052  0.89901164  0.66085481  0.43780242  0.91262149]
 [ 0.84979056  0.80388282  0.45739852  0.89799076  0.68697056]
 [ 0.25684535  0.14896382  0.02721439 -0.10862499 -0.01333101]]


# Prediction Data set


In [12]:
v2 = [0,2.77,5.55,8.33,11.11,13.88,16.66,19.44,22.22,25,27.77,30.55,33.33,36.11,38.88,41.66]
v1 = [1,3,4,8.33,12,12,15,21,23,24,28,32,30,33,41,41.66]
len(v2)

16

In [13]:
r = []
for i in range(len(v1)):
    if(i==0):
        a = 1
    else:
        a = 2.77
        
    x = v2[i]/2.5
    d=(pow((v2[i]-v1[i]),2)/(2*a))
    rg = float(x+d)
    r.append(rg)


In [14]:
r

[0.5,
 1.117548736462094,
 2.6536642599277975,
 3.332,
 4.586978339350181,
 6.189978339350182,
 7.161400722021661,
 8.21527797833935,
 8.997819494584839,
 10.180505415162456,
 11.117548736462094,
 12.599512635379062,
 15.333606498194943,
 16.18986642599278,
 16.363263537906136,
 16.663999999999998]

In [15]:
tolerance = []
for i in range(len(r)):
    t = r[i]*0.3
    tolerance.append(t)

tolerance

[0.15,
 0.3352646209386282,
 0.7960992779783392,
 0.9995999999999999,
 1.3760935018050542,
 1.8569935018050545,
 2.1484202166064983,
 2.4645833935018047,
 2.6993458483754513,
 3.054151624548737,
 3.335264620938628,
 3.7798537906137186,
 4.600081949458483,
 4.856959927797834,
 4.9089790613718405,
 4.999199999999999]

In [16]:
final_range = []
for i in range(len(r)):
    s = float(tolerance[i] + r[i])
    final_range.append(s)

final_range

[0.65,
 1.4528133574007223,
 3.449763537906137,
 4.3316,
 5.9630718411552355,
 8.046971841155237,
 9.309820938628159,
 10.679861371841154,
 11.69716534296029,
 13.234657039711193,
 14.452813357400721,
 16.37936642599278,
 19.933688447653424,
 21.046826353790614,
 21.272242599277977,
 21.663199999999996]

In [ ]:
import xlwt
from xlwt import Workbook

wb = Workbook()
  
sheet1 = wb.add_sheet('Sheet 1')

sheet1.write(0, 0, 'Self Velocity in km/hr')
sheet1.write(0, 1, 'Self Velocity in m/s')
sheet1.write(0, 2, 'Range')
sheet1.write(0, 3, 'Tolerance')
sheet1.write(0, 4, 'Range + Tolerance')

temp = 0
for i in range(len(r)):
    j = i+1
    sheet1.write(j,0,temp)
    sheet1.write(j,1,v2[i])
    sheet1.write(j,2,r[i])
    sheet1.write(j,3,tolerance[i])
    sheet1.write(j,4,final_range[i])
    temp = temp+10

wb.save('PredictedData.xls')